name: Release Testing
on:
  push:
      branches:
      - main            
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Repository
          uses: actions/Checkout@v2
        - name: Set up PostgreSQL
          run: sudo apt-get install -y postgresql 
          
        - name: Deploy Database Query
          run: | 
             mydatabase= "prod"
             SQL_FILE= "./db/test.sql"
             psql -h $localhost -p 5432 -U ${{secrets.DB_USERNAME}} -d ${{secrets.MYDATABASE}} -W ${{secrets.DB_PASSWORD}} -f $SQL_FILE