name: Release Testing
on:
  push:
      branches:
      - main            
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Repository
          uses: actions/Checkout@v2
        - name: Set up PostgreSQL
          run: sudo apt-get install -y postgresql 
          
        - name: Deploy Database Query
          run: | 
             DB_USER= ${{secrets.DB_USERNAME}}
             DB_PASSWORD= ${{secrets.DB_PASSWORD}}
             mydatabase= "prod"
             SQL_FILE= "./db/test.sql"
             psql -h $localhost -p 5432 -U $DB_USER -d $mydatabase -W $DB_PASSWORD -f $SQL_FILE