name: Release Testing
on:
  push:
      branches:
      - main            
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Repository
          uses: actions/Checkout@v2
        - name: Set up PostgreSQL
          run: sudo apt-get install -y postgresql 
        - name: Grant execute permission to SQL script
          run: chmod +x ./db/test.sql   
        - name: Deploy Database Query
          run: | 
             psql -h localhost -p 5432 -U ${{secrets.DB_USERNAME}} -d ${{secrets.MYDATABASE}} -W ${{secrets.DB_PASSWORD}} -f ./db/test.sql